
version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_fitness
    restart: always
    environment:
      POSTGRES_USER: postgres_fitness
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fitness_user_db
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
        - fitness_network

volumes:
    postgres_data:

networks:
  fitness_network:
    driver: bridge

