spring:
    application:
        name: API-Gateway
    cloud:
        gateway:
            routes:
                - id: activity-service
                  uri: lb://user-service
                  predicates:
                        - Path=/api/users/**
server:
        port: 8080

eureka:
    client:
        service-url:
            defaultZone: http://localhost:8761/eureka/
