spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5434/fitness_user_db
    username: postgres_fitness
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true

server:
  port: 8082

eureka:
    client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
